// NERDC reference curriculum seed data (JSS1 sample subjects)
export const nerdcSeedTopics: {
  classLevel: string;
  term: string;
  subject: string;
  week: number;
  topic: string;
  subTopics: string[];
}[] = [
  // ─── JSS1 English Studies ──────────────────────────────────
  ...([
    ["FIRST", 1, "Introduction to Speech; Organs of Speech", ["Organs of speech", "Speech production", "Parts of Speech: Nouns"]],
    ["FIRST", 2, "Pure Vowel Sounds (Monophthongs)", ["Identification of monophthongs", "Pronouns — meaning, types"]],
    ["FIRST", 3, "Vowel Sound /i:/", ["Verbs — definition, types", "Transitive, intransitive, auxiliary"]],
    ["FIRST", 4, "Vowel Sound /i/", ["Reading strategies", "Identifying main and supporting ideas"]],
    ["FIRST", 5, "Midterm Examination", []],
    ["FIRST", 6, "Vowel Sound /e/", ["Adjectives — types, comparison", "Paragraph writing"]],
    ["FIRST", 7, "Midterm Break", []],
    ["FIRST", 8, "Vowel Sound /ʌ/", ["Adverbs — definition, types", "Descriptive essay"]],
    ["FIRST", 9, "Vowel Sound /a:/", ["Prepositions — types and functions", "Letter writing — introduction"]],
    ["FIRST", 10, "Vowel Sound /ɒ/", ["Conjunctions — coordinating, subordinating", "Informal letter features"]],
    ["FIRST", 11, "Vowel Sound /ɔ:/", ["Adverbials — features, functions", "Figures of speech — simile, metaphor"]],
    ["FIRST", 12, "Revision", ["Review of texts", "Exam preparation"]],
    ["FIRST", 13, "Examination & Closing", []],
    ["SECOND", 1, "Vowel Sounds /u/ and /u:/", ["Adverbials of frequency and manner", "Formal letter features"]],
    ["SECOND", 2, "Vowel Sound /u:/", ["Simple Present Tense", "Introduction to poetry"]],
    ["SECOND", 3, "Vowel Sound /ɜ:/", ["Simple Past Tense", "Types of poetry — epic, lyric"]],
    ["SECOND", 4, "Vowel Sound /ɔ:/", ["Present Continuous Tense", "Drama — features, types"]],
    ["SECOND", 5, "Midterm Examination", []],
    ["SECOND", 6, "Vowel Sound /ɒ/", ["Past Continuous Tense", "Argumentative essay"]],
    ["SECOND", 7, "Midterm Break", []],
    ["SECOND", 8, "Vowel Contrasts /ɒ/ vs /ɔ:/", ["Making sentences with tenses", "Myths and legends"]],
    ["SECOND", 9, "Vowel Contrasts /e/ vs /ɜ:/", ["Future Tense", "Word formation — prefixes"]],
    ["SECOND", 10, "Introduction to Diphthongs", ["Sentence construction", "Dramatization"]],
    ["SECOND", 11, "General Revision", []],
    ["SECOND", 12, "End of Term Examination", []],
    ["SECOND", 13, "Closing", []],
    ["THIRD", 1, "Diphthongs: /ei/, /əʊ/, /aʊ/, /ɪə/, /eə/, /ɔɪ/, /aɪ/, /ʊə/", ["Active and Passive Voice introduction"]],
    ["THIRD", 2, "Identification of Diphthongs", ["Active Voice highlighted", "Prose text themes"]],
    ["THIRD", 3, "Consonant Sounds", ["Passive Voice with examples", "Identifying keywords"]],
    ["THIRD", 4, "Syllables — Words of 2-4 syllables", ["Active Voice exercises", "Argumentative essay"]],
    ["THIRD", 5, "Midterm Examination", []],
    ["THIRD", 6, "Syllables (continued)", ["Passive Voice exercises", "Poetry — meaning, figures of speech"]],
    ["THIRD", 7, "Midterm Break", []],
    ["THIRD", 8, "Consonant Clusters", ["Statements and Tag Questions", "Identifying topic sentences"]],
    ["THIRD", 9, "Word Boundaries — Linking Sounds", ["Polar and Tag Questions", "Expository essay"]],
    ["THIRD", 10, "Contrasting Diphthongs", ["Adverbials exercise", "Oral composition"]],
    ["THIRD", 11, "Revision", ["Review of all parts of speech"]],
    ["THIRD", 12, "End of Term Examination", []],
    ["THIRD", 13, "Closing", []],
  ] as const).map(([term, week, topic, subTopics]) => ({
    classLevel: "JSS1", term, subject: "English Studies",
    week, topic, subTopics: subTopics as unknown as string[],
  })),

  // ─── JSS1 Mathematics ──────────────────────────────────────
  ...([
    ["FIRST", 1, "Whole Numbers", ["Place value, ordering", "Properties of whole numbers"]],
    ["FIRST", 2, "LCM (Least Common Multiple)", ["Finding LCM using multiples", "Prime factorization"]],
    ["FIRST", 3, "HCF (Highest Common Factor)", ["Finding HCF using factorization methods"]],
    ["FIRST", 4, "Counting in Base 2", ["Introduction to binary number system"]],
    ["FIRST", 5, "Midterm Exams", []],
    ["FIRST", 6, "Conversion of Numbers", ["Conversion of Base 10 to binary numbers"]],
    ["FIRST", 7, "Midterm Break", []],
    ["FIRST", 8, "Fractions I", ["Types of fractions", "Proper, improper, mixed"]],
    ["FIRST", 9, "Fractions II", ["Equivalent fractions", "Comparison of fractions"]],
    ["FIRST", 10, "Basic Operations on Whole Numbers", ["Addition, subtraction", "Multiplication, division"]],
    ["FIRST", 11, "Revision & Exams", []],
    ["SECOND", 1, "Addition & Subtraction of Fractions", ["Same and different denominators"]],
    ["SECOND", 2, "Multiplication & Division of Fractions", ["Solving real-life problems with fractions"]],
    ["SECOND", 3, "Estimation & Approximation", ["Rounding off numbers", "Significant figures"]],
    ["SECOND", 4, "Numbers in Base 2 — Addition", ["Binary addition rules"]],
    ["SECOND", 5, "Midterm Exams", []],
    ["SECOND", 6, "Numbers in Base 2 — Subtraction", ["Binary subtraction rules"]],
    ["SECOND", 7, "Midterm Break", []],
    ["SECOND", 8, "Numbers in Base 2 — Multiplication", ["Binary multiplication rules"]],
    ["SECOND", 9, "Algebraic Processes I", ["Use of symbols, coefficients", "Algebraic expressions"]],
    ["SECOND", 10, "Simplification of Algebraic Expressions", ["Expanding brackets", "Collecting like terms"]],
    ["SECOND", 11, "Revision & Exams", []],
    ["THIRD", 1, "Simple Equations", ["Solving one-variable linear equations"]],
    ["THIRD", 2, "Plane Shapes", ["Properties of triangles, quadrilaterals, circles"]],
    ["THIRD", 3, "Three-Dimensional Figures", ["Cubes, cuboids, cylinders, spheres, cones"]],
    ["THIRD", 4, "Constructions", ["Basic geometric constructions using ruler and compass"]],
    ["THIRD", 5, "Midterm Exams", []],
    ["THIRD", 6, "Angles", ["Types of angles", "Angle sum properties"]],
    ["THIRD", 7, "Midterm Break", []],
    ["THIRD", 8, "Everyday Statistics I", ["Need for statistics", "Importance in daily life"]],
    ["THIRD", 9, "Everyday Statistics II", ["Methods of data collection"]],
    ["THIRD", 10, "Everyday Statistics III", ["Data presentation: tables, bar charts, pie charts"]],
    ["THIRD", 11, "Revision & Exams", []],
  ] as const).map(([term, week, topic, subTopics]) => ({
    classLevel: "JSS1", term, subject: "Mathematics",
    week, topic, subTopics: subTopics as unknown as string[],
  })),

  // ─── JSS1 Physical and Health Education ────────────────────
  ...([
    ["FIRST", 1, "Meaning of Physical Fitness", ["Definition", "Difference between fitness and health"]],
    ["FIRST", 2, "Components of Physical Fitness", ["Strength, endurance, flexibility", "Agility, speed, balance, coordination"]],
    ["FIRST", 3, "Characteristics of a Physically Fit Person", ["Stamina, resistance to illness", "Alertness, efficiency"]],
    ["FIRST", 4, "Importance of Physical Fitness", ["Health promotion", "Body development, disease prevention"]],
    ["FIRST", 5, "Midterm Exams", []],
    ["FIRST", 6, "Exercises to Develop Strength, Endurance, Flexibility", ["Push-ups, sit-ups, squats", "Jogging, stretching, rope skipping"]],
    ["FIRST", 7, "Midterm Break", []],
    ["FIRST", 8, "Safety Precautions while Performing Exercises", ["Warm-up, cool-down", "Hydration, proper kits"]],
    ["FIRST", 9, "Recreation, Leisure and Dance", ["Definitions with examples"]],
    ["FIRST", 10, "Differences between Dance, Leisure and Recreation", ["Distinct features and examples"]],
    ["FIRST", 11, "Revision & Examination", []],
    ["SECOND", 1, "Benefits of Recreation and Dance", ["Physical, mental, emotional, social benefits"]],
    ["SECOND", 2, "Athletics — Shot-Put (Basic Skills)", ["Grip, stance, holding and releasing"]],
    ["SECOND", 3, "Athletics — Execution of Shot-Put Techniques", ["Glide and rotational techniques"]],
    ["SECOND", 4, "Athletics — Discus Throw (Basic Skills)", ["Holding, swinging, throwing"]],
    ["SECOND", 5, "Midterm Exams", []],
    ["SECOND", 6, "Execution of Discus Throw Techniques", ["Body positioning, release, follow-through"]],
    ["SECOND", 7, "Midterm Break", []],
    ["SECOND", 8, "Rules Governing Shot-Put and Discus Throw", ["Regulations, fouls, measuring throws"]],
    ["SECOND", 9, "Safety Measures in Track and Field Events", ["Injury prevention, proper supervision"]],
    ["SECOND", 10, "Football", ["Basic rules, skills, team play, safety"]],
    ["SECOND", 11, "Revision & Examination", []],
    ["THIRD", 1, "Volleyball", ["Basic rules, skills, team play, safety"]],
    ["THIRD", 2, "Contact and Non-Contact Sports — Meaning", ["Explanation with examples"]],
    ["THIRD", 3, "Contact and Non-Contact Sports — Types", ["Football, boxing, rugby (contact)", "Tennis, badminton, athletics (non-contact)"]],
    ["THIRD", 4, "Benefits of Contact and Non-Contact Sports", ["Physical fitness, social interaction", "Discipline, teamwork"]],
    ["THIRD", 5, "Midterm Exams", []],
    ["THIRD", 6, "Basic Skills in Contact and Non-Contact Sports", ["Tackling, blocking, dodging, passing"]],
    ["THIRD", 7, "Midterm Break", []],
    ["THIRD", 8, "Safety Measures in Contact Sports", ["First aid, protective equipment, fair play"]],
    ["THIRD", 9, "Personal, School and Community Health", ["Determinants of health", "Heredity, environment, lifestyle"]],
    ["THIRD", 10, "Characteristics of a Healthy Person", ["Physical, mental, emotional, social well-being"]],
    ["THIRD", 11, "Revision & Examination", []],
  ] as const).map(([term, week, topic, subTopics]) => ({
    classLevel: "JSS1", term, subject: "Physical and Health Education",
    week, topic, subTopics: subTopics as unknown as string[],
  })),
];
